### ISSUE TITLE
Is it normal that after the installation SolisCloud is offline?

### ISSUE THREAD

**Issue by cgilis** [Pho3niX90/solis_modbus#45]
**Describe the bug**
On soliscloud the installation is offline

**To Reproduce**

**Expected behavior**

**Screenshots**
![CleanShot 2024-03-25 at 11 28 23@2x](https://github.com/Pho3niX90/solis_modbus/assets/62599539/6d8b293d-ecfe-41fc-b555-0921908354e3)

**Comment by 0rangutan** [comment]
Yes if you are running both the HA Integration and Solis Cloud from a single Data Logger then this is expected behaviour.
The logger can only manage a single TCP/IP connection and so Solid Cloud will drop off like this.
To run both simultaneously, you need a setup similar to this one:  https://github.com/alienatedsec/solis-ha-modbus-cloud
Its a bit of work but runs nicely - I am using Pho3niX90's integration plus Solis Cloud in parallel: https://github.com/alienatedsec/solis-ha-modbus-cloud/discussions/24

**Comment by cgilis** [comment]
Ok thx! @0rangutan
