### ISSUE TITLE
Offline in solis cloud as soon as solis_modbus is active

### ISSUE THREAD

**Issue by Jurgen-DOUCHY** [Pho3niX90/solis_modbus#91]
It seems that my inverter went offline as soon the solis_modbus went active.
Is the integration choacking the inverter?
Maybe bigger intervals are needed?

anyone else with this problem?

**Comment by 0rangutan** [comment]
Can you share more?  Where did it go offline?
If in Solis Cloud then this is because your logging dongle can only hold one TCP/IP connection at once, so once solis_modbus is active, Solis Cloud loses its connection and will appear to go offline.
See https://github.com/Pho3niX90/solis_modbus/issues/89

**Comment by 0rangutan** [comment]
Yep, your dongle lost connection because of the integration.

You need to decide whether you want to run the integration and Solis Cloud together or just choose one.

If you want both you need to implement something like this: https://github.com/alienatedsec/solis-ha-modbus-cloud
This is my workingsetup: https://github.com/alienatedsec/solis-ha-modbus-cloud/discussions/24

If you would like to have Solis Cloud working again, disable the Integration and reset the dongle (button on side of it) rather than restarting the inverter - it has nothing to do with the inverter itself.

**Comment by 0rangutan** [comment]
Assuming we have the same data logger - admin / 123456789
The password is shared between its local access point and securing the device so best changed to something more secure.
This is done under Advanced, Access Point
